---
openapi: 3.0.2
info:
  title: wings
  version: 1.0.0
  description: A rest api for wings
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    url: http://swagger.io
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/mintproject/wings/1.0.0
- url: http://petstore.swagger.io/api
paths:
  /components:
    post:
      requestBody:
        description: A new `Component` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Component'
        required: true
      responses:
        201:
          description: Successful response.
      operationId: createComponent
      summary: Create a Component
      description: Creates a new instance of a `Component`.
      security: []
  /datasets:
    post:
      requestBody:
        description: A new `Dataset` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
        required: true
      responses:
        201:
          description: Successful response.
      operationId: createDataset
      summary: Create a Dataset
      description: Creates a new instance of a `Dataset`.
      security: []
components:
  schemas:
    Error:
      required:
      - code
      - message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
    Component:
      description: ""
      required:
      - id
      type: object
      properties:
        id:
          description: The component id
          type: string
        model_catalog_uri:
          description: The model catalog id
          type: string
        wings_instance:
          $ref: '#/components/schemas/WingsInstance'
          description: ""
      example:
        id: economic-v5
        model_catalog_uri: https://w3id.org/okn/i/mint/ECONOMIC_AGGREGATE_CROP_SUPPLY
        wings_instance:
          username: user
          password: password
          domain: domain
          export_url: http://localhost:8080
          server: https://wings.mint.isi.edu  
    Dataset:
      description: ""
      required:
      - id
      type: object
      properties:
        id:
          type: string
        type: string
        data_catalog_id: string
        url: string
        wings_instance: {}
      example:
        id: pongo-production.csv
        type: economic-price
        data_catalog_id: fb1e373b-ea73-461c-ade5-52c9489dc76d
        data_catalog_uri: https://data.mint.isi.edu/files/economic//pongo-productioncost.csv
        wings_instance:
          username: user
          password: password
          domain: domain
          export_url: http://localhost:8080
          server: https://wings.mint.isi.edu          
    WingsInstance:
      description: ""
      type: object
      properties:
        username:
          description: ""
        password:
          description: ""
        domain:
          description: ""
        export_url:
          description: ""
        server:
          description: ""
      example:
        username: user
        password: password
        domain: domain
        export_url: http://localhost:8080
        server: https://wings.mint.isi.edu
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: openapi_server.controllers.user_controller.decode_token